import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

/**
 * Generates a professional PDF report for an article review.
 * @param {Object} article - Article metadata.
 * @param {Object} reviewData - The 10-component scores and comments.
 */
export const generateReviewReport = (article, reviewData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Branding
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text('CLARIO', 20, 25);
  
  doc.setFontSize(10);
  doc.text('ACADEMIC PUBLICATION PLATFORM', 20, 32);
  
  doc.setFontSize(14);
  doc.text('EXECUTIVE REVIEW SUMMARY', pageWidth - 80, 27);

  // Article Info
  doc.setTextColor(51, 65, 85); // slate-700
  doc.setFontSize(18);
  doc.text(article.title || 'Untitled Manuscript', 20, 55);
  
  doc.setFontSize(11);
  doc.text(`Author: ${article.authorName || 'Unknown'}`, 20, 65);
  doc.text(`Institution: ${article.institution || 'N/A'}`, 20, 72);
  doc.text(`Date Generated: ${new Date().toLocaleDateString()}`, pageWidth - 70, 65);

  doc.setDrawColor(226, 232, 240);
  doc.line(20, 80, pageWidth - 20, 80);

  // Comprehensive Scores Table
  const tableData = Object.entries(reviewData).map(([key, data]) => [
    key, // C1, C2, etc
    data.label || 'Unknown',
    data.score || 0,
    data.comment || 'No comments provided.'
  ]);

  doc.autoTable({
    startY: 90,
    head: [['ID', 'Component', 'Score', 'Detailed Feedback']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [51, 65, 85], textColor: [255, 255, 255] },
    columnStyles: {
      0: { cellWidth: 15 },
      1: { cellWidth: 40 },
      2: { cellWidth: 15, halign: 'center' },
      3: { cellWidth: 'auto' }
    }
  });

  // Footer
  const finalY = doc.lastAutoTable.finalY + 20;
  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text('Disclaimer: This report is generated by AI-assisted expert review. Final publication decisions rest with the journal editors.', 20, finalY);
  doc.text('© 2026 CLARIO Platform. All rights reserved.', 20, finalY + 7);

  // Save the PDF
  const filename = `CLARIO_Report_${article.title.replace(/\s+/g, '_').substring(0, 20)}.pdf`;
  doc.save(filename);
};
